### ISSUE TITLE
An error occurs when I click Show Answer Button (For any Card Type)

### ISSUE THREAD

**Issue by SajjadSedaqat** [r0uv3n/Multiple-type-fields-on-Card-for-Anki-2.1#3] opened 2021-10-27 10:33 UTC
Great Add-on thanks before any nagging  :)

An error occurs when I click Show Answer Button (For any Card Type)

An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (I had this problem with anki 2.1.48 too) (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-10-27 13:31:44

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 541, in handler
  File "C:\Users\MyUserName\AppData\Roaming\Anki2\addons21\711285688\Multiple_type_fields_on_card_for_2_1.py", line 134, in myOnTypedAnswer
    self.typedAnswer = val or [""]*len(self.typeCorrect)
TypeError: object of type 'NoneType' has no len()

**Comment by unit-of-inductance** [comment] 2022-05-03 16:33
Hi, and sorry for the late reply. On 2.1.49 I can't reproduce this behaviour (i.e. for me everything seems to work).

Do you know whether you have / had (at the point of opening this issue) any other Add-Ons installed that might change how Type fields are handled? I know that "Fill the blanks - Multiple type:cloze support", "touch screen - draw and write on your cards" and "Multi-Line Type Answer Box" all have problems with compatibility (as all of these Add-Ons need to change the same methods / functions I also need to change).

Making changes to improve compatibility would probably require rewriting significant portions of the code. I'm not opposed to doing that, but don't quite have the time currently.

Also, I have asked a question in the user forums whether supporting multiple type fields might be something which could be added to Anki itself (i.e. if the changes this Add-On makes could be incorporated into the original code). If that pans out, a rewrite would probably not be necessary. 

In any case, I think I'm going to wait for their answer before deciding how to proceed.

Still, if anyone has a Pull Request with a fix, I'd gladly take it!

**Comment by unit-of-inductance** [comment] 2023-05-19 18:54
I'll close this for now, since there is no further feedback and I can't reproduce this

**Closed as completed by unit-of-inductance** 2023-05-19 18:54 UTC
Labels: not reproducable
