### ISSUE TITLE
The typed-in answers aren't validated with the add-on installed.

### ISSUE THREAD

**Issue by EugeneTarasenko** [r0uv3n/Multiple-type-fields-on-Card-for-Anki-2.1#14] opened 2024-12-01 01:25 UTC
The validation won't work with this add-on (even if every other add-on is disabled.)

Front Side:
<img width="308" alt="Screen Shot 2024-12-01 at 03 24 17" src="https://github.com/user-attachments/assets/c0dc6f94-1e8e-46a3-a637-fae4216b5685">

Back Side:
<img width="170" alt="Screen Shot 2024-12-01 at 03 19 53" src="https://github.com/user-attachments/assets/c550c1aa-ba6b-49fc-a49d-9cfd16a0fa13">

MacOS 12.7.6
Anki Version 24.06.3 (d678e393)
Python 3.9.18 Qt 5.14.2 PyQt 5.14.1

**Comment by unit-of-inductance** [comment] 2024-12-08 05:12
Hmm, I just tested this on my machine with Anki 24.06.3, and did not have any problems. Could you send yourcard template for which validation fails maybe for further debugging?

**Comment by unit-of-inductance** [comment] 2024-12-08 05:13
Wait, what happens if you enter some text? I think this behavior is exactly what is expected. When you actually get something correct, the answer is marked in green, and when you type in something wrong you'll get your mistakes marked.

**Comment by EugeneTarasenko** [comment] 2024-12-08 05:51
There is no validation in any case:

![grEYtl95oIo780Kf](https://github.com/user-attachments/assets/dce91bf4-7b78-49e6-86d2-daf319b27158)
<img width="951" alt="Screen Shot 2024-12-08 at 07 44 18" src="https://github.com/user-attachments/assets/45cf877d-e145-4548-a3ea-667063fbdeb8">
<img width="1072" alt="Screen Shot 2024-12-08 at 07 44 24" src="https://github.com/user-attachments/assets/fb78a5c3-f289-44a9-99fe-2847ba1da513">
<img width="1072" alt="Screen Shot 2024-12-08 at 07 44 29" src="https://github.com/user-attachments/assets/be7c41d3-5365-4c6d-a691-9988f717797d">

I have tried using the add-on with both the Anki Qt5 and Qt6 versions, and the issue occurs in both.

**Comment by unit-of-inductance** [comment] 2024-12-08 10:43
Hmm very weird I have the exact same setup now except I'm on Linux vs MacOS and have Qt6.6.2 (PyQt 6.6.1). With the same cards and everything I get the expected behavior. 

Are you sure the Addon is updated? Could you paste the contents of the `meta.json` file which you can find by clicking `View Files` in the Addon screen?

**Comment by EugeneTarasenko** [comment] 2024-12-08 10:45
`{"name": "Multiple type fields on card for 21", "mod": 1684522243, "min_point_version": 56, "max_point_version": 63, "branch_index": 1, "disabled": true, "conflicts": [], "update_enabled": true}`

**Comment by unit-of-inductance** [comment] 2024-12-08 10:55
Could you [open the Debug console](https://docs.ankiweb.net/misc.html#debug-console), type in `pp(mw.reviewer.__dict__)` and paste the output into a comment here?

**Comment by unit-of-inductance** [comment] 2024-12-08 10:56
> `{"name": "Multiple type fields on card for 21", "mod": 1684522243, "min_point_version": 56, "max_point_version": 63, "branch_index": 1, "disabled": true, "conflicts": [], "update_enabled": true}`

Wait, I think your Addon is disabled. This output seems weird.

**Comment by EugeneTarasenko** [comment] 2024-12-08 10:58
> > `{"name": "Multiple type fields on card for 21", "mod": 1684522243, "min_point_version": 56, "max_point_version": 63, "branch_index": 1, "disabled": true, "conflicts": [], "update_enabled": true}`
> 
> Wait, I think your Addon is disabled. This output seems weird.

Yep, sorry. I disabled it temporarily. Here is the updated `meta.json` when the add-on is being enabled:

`{"name": "Multiple type fields on card for 21", "mod": 1684522243, "min_point_version": 56, "max_point_version": 63, "branch_index": 1, "disabled": false, "conflicts": [], "update_enabled": true}`

**Comment by unit-of-inductance** [comment] 2024-12-08 11:01
Okay that's exactly what I have as well.

**Comment by EugeneTarasenko** [comment] 2024-12-08 11:01
> Could you [open the Debug console](https://docs.ankiweb.net/misc.html#debug-console), type in `pp(mw.reviewer.__dict__)` and paste the output into a comment here?

```
>>> pp(mw.reviewer.__dict__)
{'_answeredIds': [],
 '_card_info': <aqt.browser.card_info.ReviewerCardInfo object at 0x11ca3efa0>,
 '_combining': True,
 '_initWeb': <function wrapInitWeb.<locals>._initReviewerWeb at 0x11f78e1f0>,
 '_previous_card_info': <aqt.browser.card_info.PreviousReviewerCardInfo object at 0x11ca3e5e0>,
 '_recordedAudio': None,
 '_refresh_needed': None,
 '_reps': None,
 '_show_answer_timer': None,
 '_show_question_timer': None,
 '_state_mutation_js': None,
 '_state_mutation_key': '17603327614073219901',
 '_states_mutated': True,
 '_v3': None,
 'auto_advance_enabled': False,
 'bottom': <aqt.toolbar.BottomBar object at 0x11ca3e910>,
 'card': None,
 'mw': <aqt.main.AnkiQt object at 0x1193f1430>,
 'previous_card': None,
 'state': None,
 'typeCorrect': None,
 'web': <aqt.main.MainWebView object at 0x11ca16ee0>}

**Comment by unit-of-inductance** [comment] 2024-12-08 11:02
Ah wait can you do this after you have answered the card?

**Comment by EugeneTarasenko** [comment] 2024-12-08 11:04
> Ah wait can you do this after you have answered the card?

```
>>> pp(mw.reviewer.__dict__)
{'_answeredIds': [],
 '_card_info': <aqt.browser.card_info.ReviewerCardInfo object at 0x11ca3efa0>,
 '_combining': True,
 '_initWeb': <function wrapInitWeb.<locals>._initReviewerWeb at 0x11f78e1f0>,
 '_previous_card_info': <aqt.browser.card_info.PreviousReviewerCardInfo object at 0x11ca3e5e0>,
 '_recordedAudio': None,
 '_refresh_needed': None,
 '_reps': 1,
 '_show_answer_timer': None,
 '_show_question_timer': None,
 '_state_mutation_js': '',
 '_state_mutation_key': '17603327614073219901',
 '_states_mutated': True,
 '_v3': V3CardInfo(queued_cards=cards {
  card {
    id: 1733636499533
    note_id: 1733636499530
    deck_id: 1733636336173
    mtime_secs: 1733636973
    ctype: 1
    queue: 1
    due: 1733637707
    reps: 1
    remaining_steps: 1
    original_position: 1857340
  }
  queue: LEARNING
  states {
    current {
      normal {
        learning {
          remaining_steps: 1
          scheduled_secs: 600
          elapsed_secs: 18855
        }
      }
      custom_data: ""
    }
    again {
      normal {
        learning {
          remaining_steps: 2
          scheduled_secs: 60
        }
      }
    }
    hard {
      normal {
        learning {
          remaining_steps: 1
          scheduled_secs: 600
        }
      }
    }
    good {
      normal {
        review {
          scheduled_days: 1
          ease_factor: 2.5
        }
      }
    }
    easy {
      normal {
        review {
          scheduled_days: 5
          ease_factor: 2.5
        }
      }
    }
  }
  context {
    deck_name: "Multiple Type Field Test"
    seed: 443810943880449
  }
}
learning_count: 1
, states=current {
  normal {
    learning {
      remaining_steps: 1
      scheduled_secs: 600
      elapsed_secs: 18855
    }
  }
  custom_data: ""
}
again {
  normal {
    learning {
      remaining_steps: 2
      scheduled_secs: 60
    }
  }
}
hard {
  normal {
    learning {
      remaining_steps: 1
      scheduled_secs: 600
    }
  }
}
good {
  normal {
    review {
      scheduled_days: 1
      ease_factor: 2.5
    }
  }
}
easy {
  normal {
    review {
      scheduled_days: 5
      ease_factor: 2.5
    }
  }
}
, context=deck_name: "Multiple Type Field Test"
seed: 443810943880449
),
 'auto_advance_enabled': False,
 'bottom': <aqt.toolbar.BottomBar object at 0x11ca3e910>,
 'card': <anki.cards.Card object at 0x123602d90>,
 'mw': <aqt.main.AnkiQt object at 0x1193f1430>,
 'previous_card': None,
 'state': 'answer',
 'typeCorrect': ['correct answer 1', 'correct answer 2'],
 'typeFont': 'Arial',
 'typeSize': 20,
 'typedAnswer': ['', ''],
 'web': <aqt.main.MainWebView object at 0x11ca16ee0>}

**Comment by unit-of-inductance** [comment] 2024-12-08 11:06
Hmm okay you're typedAnswers don't get populated, I'll look into what could cause that. You did enter something before printing this right?

**Comment by EugeneTarasenko** [comment] 2024-12-08 11:10
> Hmm okay you're typedAnswers don't get populated, I'll look into what could cause that. You did enter something before printing this right?

Yes, I did:
![EDNJL9lHRjnjaAqf](https://github.com/user-attachments/assets/207745ab-a741-45e2-b610-5ca078f6b2f2)
```
>>> pp(mw.reviewer.__dict__)
{'_answeredIds': [],
 '_card_info': <aqt.browser.card_info.ReviewerCardInfo object at 0x11ca3efa0>,
 '_combining': True,
 '_initWeb': <function wrapInitWeb.<locals>._initReviewerWeb at 0x11f78e1f0>,
 '_previous_card_info': <aqt.browser.card_info.PreviousReviewerCardInfo object at 0x11ca3e5e0>,
 '_recordedAudio': None,
 '_refresh_needed': None,
 '_reps': 1,
 '_show_answer_timer': None,
 '_show_question_timer': None,
 '_state_mutation_js': '',
 '_state_mutation_key': '17603327614073219901',
 '_states_mutated': True,
 '_v3': V3CardInfo(queued_cards=cards {
  card {
    id: 1733636499533
    note_id: 1733636499530
    deck_id: 1733636336173
    mtime_secs: 1733636973
    ctype: 1
    queue: 1
    due: 1733637707
    reps: 1
    remaining_steps: 1
    original_position: 1857340
  }
  queue: LEARNING
  states {
    current {
      normal {
        learning {
          remaining_steps: 1
          scheduled_secs: 600
          elapsed_secs: 19138
        }
      }
      custom_data: ""
    }
    again {
      normal {
        learning {
          remaining_steps: 2
          scheduled_secs: 60
        }
      }
    }
    hard {
      normal {
        learning {
          remaining_steps: 1
          scheduled_secs: 600
        }
      }
    }
    good {
      normal {
        review {
          scheduled_days: 1
          ease_factor: 2.5
        }
      }
    }
    easy {
      normal {
        review {
          scheduled_days: 5
          ease_factor: 2.5
        }
      }
    }
  }
  context {
    deck_name: "Multiple Type Field Test"
    seed: 443810943880449
  }
}
learning_count: 1
, states=current {
  normal {
    learning {
      remaining_steps: 1
      scheduled_secs: 600
      elapsed_secs: 19138
    }
  }
  custom_data: ""
}
again {
  normal {
    learning {
      remaining_steps: 2
      scheduled_secs: 60
    }
  }
}
hard {
  normal {
    learning {
      remaining_steps: 1
      scheduled_secs: 600
    }
  }
}
good {
  normal {
    review {
      scheduled_days: 1
      ease_factor: 2.5
    }
  }
}
easy {
  normal {
    review {
      scheduled_days: 5
      ease_factor: 2.5
    }
  }
}
, context=deck_name: "Multiple Type Field Test"
seed: 443810943880449
),
 'auto_advance_enabled': False,
 'bottom': <aqt.toolbar.BottomBar object at 0x11ca3e910>,
 'card': <anki.cards.Card object at 0x122cc08b0>,
 'mw': <aqt.main.AnkiQt object at 0x1193f1430>,
 'previous_card': None,
 'state': 'answer',
 'typeCorrect': ['correct answer 1', 'correct answer 2'],
 'typeFont': 'Arial',
 'typeSize': 20,
 'typedAnswer': ['', ''],
 'web': <aqt.main.MainWebView object at 0x11ca16ee0>}

**Comment by unit-of-inductance** [comment] 2024-12-08 11:12
Okay thank you very much, I'll try and investigate.

**Comment by unit-of-inductance** [comment] 2024-12-08 11:28
Ah one last thing, I don't think this affects anything, but could you just try if the corrections work if you use
```
<hr id=answer>
{{FrontSide}}
```
as your back template?

**Comment by EugeneTarasenko** [comment] 2024-12-08 11:31
The result is still the same:

<img width="1072" alt="Screen Shot 2024-12-08 at 13 29 56" src="https://github.com/user-attachments/assets/b5fd58cb-bd8d-41d0-8d0a-2ed4aeb3b3ab">
<img width="1082" alt="Screen Shot 2024-12-08 at 13 30 11" src="https://github.com/user-attachments/assets/4c993fa0-2a01-4024-8789-a46daa4c5648">

**Comment by EugeneTarasenko** [comment] 2024-12-08 12:24
Thank you for your attention. Here is some additional information: when the add-on is enabled, all cards with even a single 'type-in' field stop validating answers.
<img width="1074" alt="Screen Shot 2024-12-08 at 14 17 40" src="https://github.com/user-attachments/assets/5dc39aa7-6d09-43ab-9935-0fc3c3281f6a">
To troubleshoot the issue, I created a new user account on my computer, opened Anki, and installed only this add-on. The issue still occurred, even with no other add-ons installed.

**Comment by unit-of-inductance** [comment] 2024-12-08 13:45
Could you maybe install [AnkiWebView Inspector](https://ankiweb.net/shared/info/31746032), right click on the window while filling in the card to open the inspect Window, and then enter `_getTypedTexts()` in the Console?

**Comment by unit-of-inductance** [comment] 2024-12-08 13:52
Alternatively, what does the following return when entered into the Debug console from before?
```python
def setTypedAnswer(val):
  mw.reviewer.typedAnswer = val or [""] * len(self.typeCorrect)
mw.reviewer.web.evalWithCallback("_getTypedTexts()", setTypedAnswer)
pp(mw.reviewer.typedAnswer)
```

**Comment by EugeneTarasenko** [comment] 2024-12-08 13:53
> Could you maybe install [AnkiWebView Inspector](https://ankiweb.net/shared/info/31746032), right click on the window while filling in the card to open the inspect Window, and then enter `_getTypedTexts()` in the Console?

For some reason, it doesn't work for me. There is no the 'Inspect' right-click menu item:
<img width="674" alt="Screen Shot 2024-12-08 at 15 51 55" src="https://github.com/user-attachments/assets/b12d19a2-d298-4a6b-a848-fb4aeaef124c">
<img width="482" alt="Screen Shot 2024-12-08 at 15 51 31" src="https://github.com/user-attachments/assets/389e5257-487e-4b91-b2cb-696303be35c4">

**Comment by EugeneTarasenko** [comment] 2024-12-08 13:57
> Could you maybe install [AnkiWebView Inspector](https://ankiweb.net/shared/info/31746032), right click on the window while filling in the card to open the inspect Window, and then enter `_getTypedTexts()` in the Console?

<img width="1199" alt="Screen Shot 2024-12-08 at 15 56 49" src="https://github.com/user-attachments/assets/d38ca6e8-cb15-4bf5-a175-5f4620d0f68e">

**Comment by EugeneTarasenko** [comment] 2024-12-08 14:01
> Alternatively, what does the following return when entered into the Debug console from before?
> 
> ```python
> def setTypedAnswer(val):
>   mw.reviewer.typedAnswer = val or [""] * len(self.typeCorrect)
> mw.reviewer.web.evalWithCallback("_getTypedTexts()", setTypedAnswer)
> pp(mw.reviewer.typedAnswer)
> ```

<img width="663" alt="Screen Shot 2024-12-08 at 15 58 07" src="https://github.com/user-attachments/assets/3aa1dd15-0840-49c5-9eb1-310406dd170e">

```
>>> def setTypedAnswer(val):
...   mw.reviewer.typedAnswer = val or [""] * len(self.typeCorrect)
... mw.reviewer.web.evalWithCallback("_getTypedTexts()", setTypedAnswer)
... pp(mw.reviewer.typedAnswer)
['', '']
```



Debug Info:

```
Anki 24.11 (87ccd24e)  (ao)
Python 3.9.18 Qt 5.14.2 PyQt 5.14.1
Platform: macOS-12.7.6-x86_64-i386-64bit

Traceback (most recent call last):
  File "aqt.webview", line 665, in handler
  File "<string>", line 2, in setTypedAnswer
NameError: name 'self' is not defined

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Browser Play Button ['182970692', 2024-09-17T23:18, 'None', '']
AJT Merge Notes  Merge and Duplicate notes ['1425504015', 2024-09-17T22:35, 'None', '']
Additional Card Fields Fork for 21 ['744725736', 2022-10-23T13:10, 'None', '']
Advanced Copy Fields ['1898445115', 2024-01-08T19:01, 'v0.4.01', '']
AnkiConnect ['2055492159', 2024-11-07T03:34, 'None', '']
AnkiWebView Inspector ['31746032', 2023-06-27T22:26, 'None', '']
Automatically rebuild filtered deck ['1997713323', 2021-07-18T18:18, 'None', '']
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-12-06T03:28, 'None', '']
Batch Editing ['291119185', 2023-10-26T03:38, 'None', '']
Clickable Tags v20 ['1739176371', 2022-01-31T00:58, 'None', '']
Deck duplication ['1779572689', 2022-06-11T17:24, 'None', '']
Edit Field During Review Cloze ['385888438', 2024-11-16T12:23, '6.21', mod]
Fill the blanks - Multiple typecloze support ['1933645497', 2023-05-03T21:21, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T10:15, 'None', '']
More color buttons in the editor ['312062643', 2023-06-04T02:06, 'None', mod]
Multiple type fields on card for 21 ['711285688', 2023-05-19T21:50, 'None', '']
OpenInExternalEditorRenameDuplicate for ImageAudioVideo WinLinux ['1560623518', 2023-03-19T19:33, 'None', '']
Prevent Double Click ['1596656178', 2024-08-04T07:37, 'None', mod]
Quick tagging 21 ['304770511', 2020-02-11T08:17, 'None', '']
Remove Cloze Button and Hotkey ['1966460736', 2022-05-21T13:29, 'None', '']
Show Duplicates Shortcut ['689277073', 2022-11-05T03:58, 'None', '']

===IDs of active AnkiWeb add-ons===
1374772155 1425504015 1436550454 1560623518 1596656178 1739176371 1779572689 182970692 1898445115 1933645497 1966460736 1997713323 2055492159 291119185 304770511 312062643 31746032 385888438 689277073 711285688 744725736

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
```

**Comment by unit-of-inductance** [comment] 2024-12-08 14:05
Ah sorry, for the second one, please use
```python
def setTypedAnswer(val):
  mw.reviewer.typedAnswer = val or [""] * len(mw.reviewer.typeCorrect)
mw.reviewer.web.evalWithCallback("_getTypedTexts()", setTypedAnswer)
pp(mw.reviewer.typedAnswer)
```

**Comment by unit-of-inductance** [comment] 2024-12-08 14:06
But yeah the problem seems to be the html stuff. Could you put `pp(mw.reviewer.revHtml())` into the Debugger for me?

**Comment by EugeneTarasenko** [comment] 2024-12-08 14:07
Actually, I no longer need this add-on. So, if I'm the only one who encountered this issue, you don't need to bother fixing it. You can close this issue.

**Comment by EugeneTarasenko** [comment] 2024-12-08 14:08
> But yeah the problem seems to be the html stuff. Could you put `pp(mw.reviewer.revHtml())` into the Debugger for me?

```
>>> pp(mw.reviewer.revHtml())
('\n'
 '<div id="_mark" hidden>&#x2605;</div>\n'
 '<div id="_flag" hidden>&#x2691;</div>\n'
 '\n'
 '<div id="qa"></div>\n'
 '\n'
 '\n'
 '<script>\n'
 'typetxts = document.getElementsByName("typetxt");\n'
 'function _getTypedTexts(){\n'
 '    typedTexts = [];\n'
 '    for (let i = 0, typedTextNode; (typedTextNode = typetxts[i]); i++) {\n'
 '        typedTexts.push(typedTextNode.value) ?? null;\n'
 '    }\n'
 '    return typedTexts;\n'
 '}\n'
 '</script>\n')
```

**Comment by EugeneTarasenko** [comment] 2024-12-08 14:09
> Ah sorry, for the second one, please use
> 
> ```python
> def setTypedAnswer(val):
>   mw.reviewer.typedAnswer = val or [""] * len(mw.reviewer.typeCorrect)
> mw.reviewer.web.evalWithCallback("_getTypedTexts()", setTypedAnswer)
> pp(mw.reviewer.typedAnswer)
> ```

```
>>> pp(mw.reviewer.revHtml())
('\n'
 '<div id="_mark" hidden>&#x2605;</div>\n'
 '<div id="_flag" hidden>&#x2691;</div>\n'
 '\n'
 '<div id="qa"></div>\n'
 '\n'
 '\n'
 '<script>\n'
 'typetxts = document.getElementsByName("typetxt");\n'
 'function _getTypedTexts(){\n'
 '    typedTexts = [];\n'
 '    for (let i = 0, typedTextNode; (typedTextNode = typetxts[i]); i++) {\n'
 '        typedTexts.push(typedTextNode.value) ?? null;\n'
 '    }\n'
 '    return typedTexts;\n'
 '}\n'
 '</script>\n')

>>> def setTypedAnswer(val):
...   mw.reviewer.typedAnswer = val or [""] * len(mw.reviewer.typeCorrect)
... mw.reviewer.web.evalWithCallback("_getTypedTexts()", setTypedAnswer)
... pp(mw.reviewer.typedAnswer)
None
```

**Comment by unit-of-inductance** [comment] 2024-12-08 14:46
> >>> pp(mw.reviewer.revHtml())
> ('\n'
>  '<div id="_mark" hidden>&#x2605;</div>\n'
>  '<div id="_flag" hidden>&#x2691;</div>\n'
>  '\n'
>  '<div id="qa"></div>\n'
>  '\n'
>  '\n'
>  '<script>\n'
>  'typetxts = document.getElementsByName("typetxt");\n'
>  'function _getTypedTexts(){\n'
>  '    typedTexts = [];\n'
>  '    for (let i = 0, typedTextNode; (typedTextNode = typetxts[i]); i++) {\n'
>  '        typedTexts.push(typedTextNode.value) ?? null;\n'
>  '    }\n'
>  '    return typedTexts;\n'
>  '}\n'
>  '</script>\n')

Hmm, the function should really be defined then. Very weird.

**Comment by unit-of-inductance** [comment] 2024-12-08 15:19
I just pushed an update, could you try it to see if it helps? I know you no longer need this addon, but I suspect this is a MacOS / Webkit specific bug that will probably affect different people as well (even though I have not received any other bug reports yet, so really no need for you to invest more effort than you want).

**Comment by EugeneTarasenko** [comment] 2024-12-08 15:22
No avail.
<img width="866" alt="Screen Shot 2024-12-08 at 17 21 45" src="https://github.com/user-attachments/assets/c9898776-7a0f-440c-b3c2-641bbf4693c1">

**Comment by unit-of-inductance** [comment] 2024-12-08 15:24
You restarted after updating? If yes, then I'll probably just close this.

**Comment by EugeneTarasenko** [comment] 2024-12-08 15:26
Yes I did. Close it. Save your and my time. Anyway, thank you for paying attention.

**Closed as completed** 2024-12-08 15:39 UTC
